"""Stage 11 — fills README.template.md placeholders from reports/metrics/*.json
and data/dashboard/*.json. Fails loudly on any unresolved placeholder so the
README can never silently quote a number the code no longer produces
(plan sec 11.3).

Placeholder syntax: ``{{file.path.to.value}}`` or ``{{file.path|filter}}``.
The first path segment is a JSON file's stem (e.g. ``kpi_summary`` for
``data/dashboard/kpi_summary.json``); remaining segments index into the
parsed JSON (dict keys or list indices). Supported filters: comma, pct1,
pct2, round2, round4, gbp0.

Usage::

    python -m src.report_fill
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from src.config import cfg

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_PATH = REPO_ROOT / "README.template.md"
OUT_PATH = REPO_ROOT / "README.md"
METRIC_DIRS = [cfg.paths.metrics_dir, cfg.paths.dashboard_dir]

_PLACEHOLDER_RE = re.compile(r"\{\{\s*([\w\.\[\]0-9]+)\s*(?:\|\s*(\w+)\s*)?\}\}")


def load_all_metrics(dirs: list[Path] | None = None) -> dict[str, Any]:
    """Load every *.json in the given directories, keyed by filename stem."""
    dirs = dirs or METRIC_DIRS
    data: dict[str, Any] = {}
    for d in dirs:
        for p in sorted(d.glob("*.json")):
            data[p.stem] = json.loads(p.read_text())
    return data


def resolve_path(data: dict, path: str) -> Any:
    """Resolve a dotted path (list indices as plain digits) into *data*."""
    cur: Any = data
    for part in path.split("."):
        if isinstance(cur, list):
            cur = cur[int(part)]
        elif isinstance(cur, dict):
            if part not in cur:
                raise KeyError(f"'{part}' not found (path={path})")
            cur = cur[part]
        else:
            raise KeyError(f"cannot descend into {type(cur)} at '{part}' (path={path})")
    return cur


def _apply_filter(value: Any, fmt: str | None) -> str:
    if fmt is None:
        return str(value)
    if fmt == "comma":
        return f"{int(value):,}"
    if fmt == "pct1":
        return f"{float(value) * 100:.1f}%"
    if fmt == "pct2":
        return f"{float(value) * 100:.2f}%"
    if fmt == "round2":
        return f"{float(value):.2f}"
    if fmt == "round4":
        return f"{float(value):.4f}"
    if fmt == "gbp0":
        return f"£{float(value):,.0f}"
    raise ValueError(f"Unknown filter '{fmt}'")


def fill_readme(template_path: Path | None = None, out_path: Path | None = None) -> Path:
    """Replace every {{...}} placeholder in the template with a real metric value.

    Raises:
        ValueError: on the first unresolved placeholder, naming it exactly.
    """
    template_path = template_path or TEMPLATE_PATH
    out_path = out_path or OUT_PATH
    metrics = load_all_metrics()
    text = template_path.read_text(encoding="utf-8")

    unresolved: list[str] = []

    def repl(m: re.Match) -> str:
        path, fmt = m.group(1), m.group(2)
        try:
            value = resolve_path(metrics, path)
        except (KeyError, IndexError, ValueError) as exc:
            unresolved.append(f"{{{{{path}}}}} -> {exc}")
            return m.group(0)
        return _apply_filter(value, fmt)

    filled = _PLACEHOLDER_RE.sub(repl, text)

    if unresolved:
        raise ValueError("Unresolved README placeholders:\n" + "\n".join(unresolved))

    filled = filled.rstrip("\n") + "\n\n<!-- generated by src/report_fill.py from reports/metrics and data/dashboard JSON — do not hand-edit numbers -->\n"
    out_path.write_text(filled, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    path = fill_readme()
    print(f"Wrote {path}")
